# HW01 <font color=red>(제출기한-3월30일 일요일 자정)</font>
---
NumPy 이해도 평가를 위한 문제입니다.
다음 사항을 주의해서 제출하기 바랍니다.

- 각 문제에 대한 답안을 <font color=red>'답안을 작성하시오'</font>라고 적힌 <font color=red>한 코드셀 내</font>에 작성하며 셀 내에서 여러줄로 작성해도 무방합니다.
- 셀을 추가하거나 셀을 삭제하지 않습니다. 예: (<font color=red>'지우지 마시오'</font> 셀 등)
- 출력결과가 미리 제시된 셀(<font color=red>'예시 실행결과를 참조하시오.'</font>라고 표시된 셀)을 참고합니다.
- Loop를 사용하지 말고 ufunc을 활용합니다.
- 수업시간 배운 내용만을 사용하여 코드를 작성합니다.
- 문제나 제출방법에 대한 질문이 있을 경우 제출전 UCLASS 등을 통해 반드시 미리 확인합니다.

> 제출방법

- ULMS HW1 제출란에 <font color=red>'HW01-학번.ipynb'</font>(본인학번을 기입)을 기한내 업로드합니다.


### 가정
- 아래에서 생성된 _score_ 변수는 $20 \times 4$ 크기의 2차원 numpy array이다.
- 이는 10명 학생의 국어, 영어, 수학, 사회 점수(1번째부터 3번째 열 순서)를 각각 나타낸다. (0점~100점)

In [10]:
### 지우지 마시오.
import numpy as np
rng=np.random.RandomState(765)
score=rng.randint(20, 101,(10,4))
score

array([[49, 24, 66, 47],
       [90, 99, 80, 39],
       [20, 58, 38, 85],
       [36, 27, 62, 56],
       [84, 37, 28, 49],
       [75, 75, 26, 44],
       [22, 60, 26, 45],
       [85, 30, 99, 69],
       [40, 25, 81, 57],
       [45, 98, 64, 57]])

### 문제1
가장 마지막 학생의 수학 점수가 64점이 아니라 46점이라고 한다.

이렇게 *score* 배열을 수정하기 위한 코드를 작성하시오.

In [11]:
### 답안을 작성하시오.
score[9][2] = 46
score

array([[49, 24, 66, 47],
       [90, 99, 80, 39],
       [20, 58, 38, 85],
       [36, 27, 62, 56],
       [84, 37, 28, 49],
       [75, 75, 26, 44],
       [22, 60, 26, 45],
       [85, 30, 99, 69],
       [40, 25, 81, 57],
       [45, 98, 46, 57]])

In [3]:
### 예시 실행결과를 참조하시오.
score

array([[49, 24, 66, 47],
       [90, 99, 80, 39],
       [20, 58, 38, 85],
       [36, 27, 62, 56],
       [84, 37, 28, 49],
       [75, 75, 26, 44],
       [22, 60, 26, 45],
       [85, 30, 99, 69],
       [40, 25, 81, 57],
       [45, 98, 46, 57]])

### 문제2
위 결과 이후 채점에 오류가 발견되어 모든 학생들의 영어점수를 5점씩 줄여야 한다고 한다. 이렇게 *score* 배열을 수정하기 위한 코드를 작성하시오.

In [12]:
### 답안을 작성하시오.
score[:, 1] -= 5
score

array([[49, 19, 66, 47],
       [90, 94, 80, 39],
       [20, 53, 38, 85],
       [36, 22, 62, 56],
       [84, 32, 28, 49],
       [75, 70, 26, 44],
       [22, 55, 26, 45],
       [85, 25, 99, 69],
       [40, 20, 81, 57],
       [45, 93, 46, 57]])

In [5]:
### 예시 실행결과를 참조하시오.
score

array([[49, 19, 66, 47],
       [90, 94, 80, 39],
       [20, 53, 38, 85],
       [36, 22, 62, 56],
       [84, 32, 28, 49],
       [75, 70, 26, 44],
       [22, 55, 26, 45],
       [85, 25, 99, 69],
       [40, 20, 81, 57],
       [45, 93, 46, 57]])

### 문제3
새로운 음악, 미술 과목의 시험 점수가 다음 _score\_add_ 변수에 주어진다. 이를 _score_ 변수 데이터에 덧붙여 총 6개 과목의 데이터를 *score_all*변수에 다시 저장하고자 한다. 이를 위한 코드를 작성하시오.

In [ ]:
### 지우지 마시오.
score_add=rng.randint(20, 101,(10,2)) # rng로 인해 시드 고정이지만 값이 바뀐다. 하지만 여러번 반복하니 바뀌는 값들이 일정하다.
score_add

array([[58, 66],
       [60, 77],
       [46, 29],
       [86, 66],
       [26, 53],
       [83, 53],
       [76, 89],
       [92, 90],
       [70, 95],
       [24, 47]])

In [21]:
### 답안을 작성하시오.
score_all = np.hstack([score, score_add])
score_all

array([[49, 19, 66, 47, 58, 66],
       [90, 94, 80, 39, 60, 77],
       [20, 53, 38, 85, 46, 29],
       [36, 22, 62, 56, 86, 66],
       [84, 32, 28, 49, 26, 53],
       [75, 70, 26, 44, 83, 53],
       [22, 55, 26, 45, 76, 89],
       [85, 25, 99, 69, 92, 90],
       [40, 20, 81, 57, 70, 95],
       [45, 93, 46, 57, 24, 47]])

In [ ]:
### 예시 실행결과를 참조하시오.
score_all

array([[49, 19, 66, 47, 58, 66],
       [90, 94, 80, 39, 60, 77],
       [20, 53, 38, 85, 46, 29],
       [36, 22, 62, 56, 86, 66],
       [84, 32, 28, 49, 26, 53],
       [75, 70, 26, 44, 83, 53],
       [22, 55, 26, 45, 76, 89],
       [85, 25, 99, 69, 92, 90],
       [40, 20, 81, 57, 70, 95],
       [45, 93, 46, 57, 24, 47]])

### 문제4
위 결과 *score_all* array에 대해 과목별 평균점수를 뜻하는 _avg\_subject_ array(1차원)를 구하는 코드를 작성하시오.

In [22]:
### 답안을 작성하시오.
avg_subject = np.mean(score_all, axis=0)
avg_subject

array([54.6, 48.3, 55.2, 54.8, 62.1, 66.5])

In [ ]:
### 예시 실행결과를 참조하시오.
avg_subject

array([54.6, 48.3, 55.2, 54.8, 62.1, 66.5])

### 문제5
비슷하게 *score* array에 대해 학생별 평균점수를 뜻하는 _avg\_student_ array(1차원)를 구하는 코드를 작성하시오.

In [23]:
### 답안을 작성하시오.
avg_student = np.mean(score_all, axis = 1) # score가 아니라 score_all
avg_student

array([50.83333333, 73.33333333, 45.16666667, 54.66666667, 45.33333333,
       58.5       , 52.16666667, 76.66666667, 60.5       , 52.        ])

In [ ]:
### 예시 실행결과를 참조하시오.
avg_student

array([50.83333333, 73.33333333, 45.16666667, 54.66666667, 45.33333333,
       58.5       , 52.16666667, 76.66666667, 60.5       , 52.        ])

### 문제6
각 점수가 해당과목의 평균으로부터 얼마나 차이가 나는지(이를 편차라고 한다.)를 나타내는 _score\_dev_ array(2차원)를 생성하시오.
- score_dev의 shape는 score의 shape와 동일하다. 즉 score_dev.shape=(20, 6)
- 만약 어떤 학생의 국어 점수가 30점이고 전체 학생의 국어 평균이 45점이면 그 차이(편차)는 $30-45=-15$ 점이다.

---
참고) _score\_dev_ 의 axis=0 방향 평균값이 어떻게 될 지 생각해 보자.


In [24]:
### 답안을 작성하시오.
'''print(f'학생들의 점수 : \n{score_all}')
print(f"각 과목별 평균 : {np.mean(score_all, axis = 0)}")
print(f"편차 : \n{score_all - np.mean(score_all, axis = 0)}")'''

score_dev = score_all - avg_subject
score_dev

array([[ -5.6, -29.3,  10.8,  -7.8,  -4.1,  -0.5],
       [ 35.4,  45.7,  24.8, -15.8,  -2.1,  10.5],
       [-34.6,   4.7, -17.2,  30.2, -16.1, -37.5],
       [-18.6, -26.3,   6.8,   1.2,  23.9,  -0.5],
       [ 29.4, -16.3, -27.2,  -5.8, -36.1, -13.5],
       [ 20.4,  21.7, -29.2, -10.8,  20.9, -13.5],
       [-32.6,   6.7, -29.2,  -9.8,  13.9,  22.5],
       [ 30.4, -23.3,  43.8,  14.2,  29.9,  23.5],
       [-14.6, -28.3,  25.8,   2.2,   7.9,  28.5],
       [ -9.6,  44.7,  -9.2,   2.2, -38.1, -19.5]])

In [ ]:
### 예시 실행결과를 참조하시오.
score_dev

array([[ -5.6, -29.3,  10.8,  -7.8,  -4.1,  -0.5],
       [ 35.4,  45.7,  24.8, -15.8,  -2.1,  10.5],
       [-34.6,   4.7, -17.2,  30.2, -16.1, -37.5],
       [-18.6, -26.3,   6.8,   1.2,  23.9,  -0.5],
       [ 29.4, -16.3, -27.2,  -5.8, -36.1, -13.5],
       [ 20.4,  21.7, -29.2, -10.8,  20.9, -13.5],
       [-32.6,   6.7, -29.2,  -9.8,  13.9,  22.5],
       [ 30.4, -23.3,  43.8,  14.2,  29.9,  23.5],
       [-14.6, -28.3,  25.8,   2.2,   7.9,  28.5],
       [ -9.6,  44.7,  -9.2,   2.2, -38.1, -19.5]])

### 문제7
위 *avg_student*를 이용하여 전체과목 평균점수를 기준으로 1등과 10등을 한 학생들이 몇 번째 학생인지를 각각 *student_best*와 *student_worst*에 각각 저장하시오.
- 결과값은 1이상 10이하의 자연수이다.

In [25]:
### 답안을 작성하시오.
student_best = np.argmax(avg_student) + 1
student_worst = np.argmin(avg_student) + 1

print(f"1등 : {student_best}번째 학생, 10등 : {student_worst}번째 학생")

1등 : 8번째 학생, 10등 : 3번째 학생


In [ ]:
### 예시 실행결과를 참조하시오.
student_best, student_worst

(np.int64(8), np.int64(3))

### 문제8
위 avg_student를 이용하여 전체 학생의 평균점수를 구하여 _avg\_total_ 변수에 저장하시오.

In [26]:
### 답안을 작성하시오.
avg_total = np.mean(avg_student)
avg_total

56.91666666666667

In [ ]:
### 예시 실행결과를 참조하시오.
avg_total

np.float64(56.91666666666667)

### 문제9
전체 평균 점수(_avg\_total_) 보다 높은 평균 점수를 얻은 학생의 수를 구하여 _no\_student\_high_ 변수에 저장하시오.  

In [27]:
### 답안을 작성하시오.
'''
print(f"{avg_student}중 {avg_total} 보다 큰 것 : {avg_student > avg_total}")
'''
no_student_high = np.sum(avg_student > avg_total)
no_student_high

4

In [ ]:
### 예시 실행결과를 참조하시오.
no_student_high

np.int64(4)

### 문제10
수학점수가 국어점수와 영어점수보다 모두 더 높은 학생 수를 구하여 _no\_student\_math_ 변수에 저장하시오.


In [28]:
### 답안을 작성하시오.

# 국, 영, 수, 사
'''print(f"전체 스코어 : \n{score_all}\n 그 중 수학점수 : \n{score_all[:, 2]}")
print(f"국어보다 수학이 높은 학생 : \n{score_all[:, 2] > score_all[:, 0]}\n영어보다 수학이 높은 학생 : \n{score_all[:, 2] > score_all[:, 1]}")
print(f"둘 다 True인 경우 : {np.sum((score_all[:, 2] > score_all[:, 0]) & (score_all[:, 2] > score_all[:, 1]))}명")'''

no_student_math = np.sum((score_all[:, 2] > score_all[:, 0]) & (score_all[:, 2] > score_all[:, 1]))
no_student_math

4

In [ ]:
### 예시 실행결과를 참조하시오.
no_student_math

np.int64(4)