In [1]:
import numpy as np
import pandas as pd

# Fancy Indexing

In [2]:
rand = np.random.RandomState(42)

x = rand.randint(100, size = 10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [ ]:
ind = [3, 7, 4]

print(f"일반적인 인덱싱 : {[x[3], x[7], x[2]]}")
print(f"리스트 삽입 : {x[[3, 7, 4]]}")
print(f"ind 리스트트 사용 : {x[ind]}")

일반적인 인덱싱 : [71, 86, 14]
리스트 삽입 : [71 86 60]
ind 객체 사용 : [71 86 60]


In [6]:
ind = np.array([[3, 7],
                [4, 5]])

print(f"1차원 인덱싱 : {x[[3, 7, 4, 5]]}")
print(f"2차원 인덱싱 : \n{x[ind]}")

1차원 인덱싱 : [71 86 60 20]
2차원 인덱싱 : 
[[71 86]
 [60 20]]


### 2차원에서의 Fancy Indexing

In [17]:
x = np.arange(12).reshape((3, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])

print(f"[0, 2] : {x[0][2]}, [1, 1] : {x[1][1]}, [2, 3] : {x[2][3]}")
print(f"{x[row, col]}")

[0, 2] : 2, [1, 1] : 5, [2, 3] : 11
[ 2  5 11]


### Broadcasting에서의 Fancy Indexing

In [19]:
print(f"row[:, np.newaxis]의 결과는 \n{row[:, np.newaxis]}이고, 이는 \n[[0, 0, 0], \n [1, 1, 1], \n [2, 2, 2]]가 된다\n")
print(f"col은 {col}이고, \n[[2, 1, 3], \n [2, 1, 3], \n [2, 1, 3]]이다\n")

print(f"따라서 X[row[:, np.newaxis], col]는 (0, 0)에 x[0][2], (0, 1)에 x[0][1] 순으로 들어가게 된다.\n{X[row[:, np.newaxis], col]}")

row[:, np.newaxis]의 결과는 
[[0]
 [1]
 [2]]이고, 이는 
[[0, 0, 0], 
 [1, 1, 1], 
 [2, 2, 2]]가 된다

col은 [2 1 3]이고, 
[[2, 1, 3], 
 [2, 1, 3], 
 [2, 1, 3]]이다

따라서 X[row[:, np.newaxis], col]는 (0, 0)에 x[0][2], (0, 1)에 x[0][1] 순으로 들어가게 된다.
[[ 2  1  3]
 [ 6  5  7]
 [10  9 11]]


In [31]:
print(f"""{row[:, np.newaxis]} * {col}는 \n\n[[0, 0, 0], \t[[2, 1, 3],\n [1, 1, 1],  *   [2, 1, 3],\n [2, 2, 2]] \t [2, 1, 3]]\n
{row[:, np.newaxis] * col}이다\n""")

[[0]
 [1]
 [2]] * [2 1 3]는 

[[0, 0, 0], 	[[2, 1, 3],
 [1, 1, 1],  *   [2, 1, 3],
 [2, 2, 2]] 	 [2, 1, 3]]

[[0 0 0]
 [2 1 3]
 [4 2 6]]이다



# Combined Indexing

In [42]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
print(f"x[2][2] : {x[2][2]}, x[2][0] : {x[2][0]}, x[2][1] : {x[2][1]}")
print(f"x[2, [2, 0, 1]] : {x[2, [2, 0, 1]]}")

X[2, [2, 0, 1]] # [X[2][2], X[2][0], X[2][1]]

x[2][2] : 10, x[2][0] : 8, x[2][1] : 9
x[2, [2, 0, 1]] : [10  8  9]


array([10,  8,  9])

In [ ]:
X[1:, [2, 0, 1]] # [X[1][2], X[1][0], X[1][1], X[2][2], X[2][0], X[2][1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [52]:
row[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [55]:
mask

array([ True, False,  True, False])

In [58]:
mask = np.array([1, 0, 1, 0], dtype = bool)
X[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [65]:
print(f"""row[:, np.newaxis] : \n{row[:, np.newaxis]}와 \nmask : {mask}를 합치게 되면\n
[[True, False, True, False],
 [True, False, True, False],
 [True, False, True, False]] 가 된다.

따라서 X[row[:, np.newaxis], mask]는
{X[row[:, np.newaxis], mask]}이다""")

row[:, np.newaxis] : 
[[0]
 [1]
 [2]]와 
mask : [ True False  True False]를 합치게 되면

[[True, False, True, False],
 [True, False, True, False],
 [True, False, True, False]] 가 된다.

따라서 X[row[:, np.newaxis], mask]는
[[ 0  2]
 [ 4  6]
 [ 8 10]]이다


# Example : Selecting Random Points

In [ ]:
# 나중에

# Fancy Indexing을 이용한 값 변경

In [73]:
x = np.arange(10)
print(f"변환 전 x : {x}")
i = np.array([2, 1, 8, 4])
x[i] = 99

print(f"""x[i] = 99는 [x[2], x[1], x[8], x[4]] = 99를 의미한다.
변환 후 x : {x}이다""")

변환 전 x : [0 1 2 3 4 5 6 7 8 9]
x[i] = 99는 [x[2], x[1], x[8], x[4]] = 99를 의미한다.
변환 후 x : [ 0 99 99  3 99  5  6  7 99  9]이다


In [ ]:
print(f"x[i] -= 10는 [x[2], x[1], x[8], x[4]] 를 10씩 빼는 것을 의미한다.")
print(x)

x[i] -= 10는 [x[2], x[1], x[8], x[4]] 를 10씩 빼는 것을 의미한다.

[ 0 89 89  3 89  5  6  7 89  9]


In [104]:
x = np.zeros(10)
x[[0, 0]] = [4, 6]
print(x)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
x = np.zeros(10)
print(f"0에 4 넣고, 0에 6을 넣어라 : {x[[0, 0]] = [4, 6]}") # Error

SyntaxError: f-string: expecting '!', or ':', or '}' (3245715125.py, line 2)

In [ ]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1 # 실제로 연산을 진행하면 한 번 실행된다.
x

array([6., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

In [ ]:
x = np.zeros(10)
np.add.at(x, i, 1) # add연산은 + 연산과는 다르게 여러 번 실행된다.
print(x)

[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


# Example: Binning Data

In [108]:
# 나중에