In [1]:
import numpy as np

# Sorting Arrays

In [2]:
def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    
    return x

In [3]:
x = np.array([2, 1, 4, 3, 5])
selection_sort(x)

array([1, 2, 3, 4, 5])

In [20]:
x = np.array([2, 1, 4, 3, 5])
np.argmin(x[:4]) # 인덱싱 한 구간에서 최소값의 인덱스 출력

1

### Bogo Sort - 저자가 만든 알고리즘.

In [17]:
def bogosort(x):
    while (np.any(x[:-1] > x[1:])):
        np.random.shuffle(x)

    return x

In [21]:
x = np.array([2, 1, 4, 3, 5])
%timeit selection_sort(x)
%timeit bogosort(x)

12.7 μs ± 340 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
5.33 μs ± 215 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Fast Sorting

In [22]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [23]:
x.sort()
x

array([1, 2, 3, 4, 5])

In [24]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [25]:
x[i]

array([1, 2, 3, 4, 5])

### 행,열 방향 정렬

In [27]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [28]:
np.sort(X, axis = 0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [29]:
np.sort(X, axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

# Partial Sort

In [30]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

# Example : K-Nearest Neighbors