In [1]:
import numpy as np
import pandas as pd

# Fancy Indexing

In [2]:
rand = np.random.RandomState(42)

x = rand.randint(100, size = 10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [9]:
ind = [3, 7, 4]

print(f"일반적인 인덱싱 : {[x[3], x[7], x[2]]}")
print(f"리스트 삽입 : {x[[3, 7, 4]]}")
print(f"ind 객체 사용 : {x[ind]}")

일반적인 인덱싱 : [71, 86, 14]
리스트 삽입 : [71 86 60]
ind 객체 사용 : [71 86 60]


In [10]:
ind = np.array([[3, 7],
                [4, 5]])

x[ind]

array([[71, 86],
       [60, 20]])

### 2차원에서의 Fancy Indexing

In [11]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

### Broadcasting에서의 Fancy Indexing

In [27]:
print(f"row[:, np.newaxis]의 결과는 \n{row[:, np.newaxis]}이고, 이는 \n[[0, 0, 0], \n [1, 1, 1], \n [2, 2, 2]]가 된다\n")
print(f"col은 {col}이고, \n[[2, 1, 3], \n [2, 1, 3], \n [2, 1, 3]]이다\n")

print(f"따라서 X[row[:, np.newaxis], col]는 (0, 0)에 x[0][2], (0, 1)에 x[0][1] 순으로 들어가게 된다.\n{X[row[:, np.newaxis], col]}")

row[:, np.newaxis]의 결과는 
[[0]
 [1]
 [2]]이고, 이는 
[[0, 0, 0], 
 [1, 1, 1], 
 [2, 2, 2]]가 된다

col은 [2 1 3]이고, 
[[2, 1, 3], 
 [2, 1, 3], 
 [2, 1, 3]]이다

따라서 X[row[:, np.newaxis], col]는 (0, 0)에 x[0][2], (0, 1)에 x[0][1] 순으로 들어가게 된다.
[[ 2  1  3]
 [ 6  5  7]
 [10  9 11]]


In [28]:
row[:, np.newaxis] * col

array([[0, 0, 0],
       [2, 1, 3],
       [4, 2, 6]])

# Combined Indexing

In [29]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [32]:
X[2, [2, 0, 1]] # [X[2][2], X[2][0], X[2][1]]

array([10,  8,  9])

In [31]:
X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [33]:
mask = np.array([1, 0, 1, 0], dtype = bool)
X[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

# Example : Selecting Random Points

In [ ]:
# 나중에

# Fancy Indexing을 이용한 값 변경

In [34]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [52]:
x = np.zeros(10)
print(f"0에 4 넣고, 0에 6을 넣어라 : {x[[0, 0]] = [4, 6]}")

SyntaxError: f-string: expecting '!', or ':', or '}' (3245715125.py, line 2)

In [53]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1
x

array([0., 0., 1., 1., 1., 0., 0., 0., 0., 0.])