# Reshaping of Arrays

In [2]:
import numpy as np

### 1x9 를 3x3으로 변환

In [4]:
grid = np.arange(1, 10).reshape(3, 3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

### 행, 열을 늘려주는 메소드

In [22]:
# 행 증가
x[np.newaxis, :]

array([[1, 2, 3]])

In [23]:
# 열 증가
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [31]:
x[np.newaxis, :][0]

array([1, 2, 3])

In [36]:
x[:, np.newaxis][1]

array([2])

# Array Concatenaion and Splitting

In [37]:
# Concatenate
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [43]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [45]:
# vertical stack
np.vstack([x, y, z])

array([[ 1,  2,  3],
       [ 3,  2,  1],
       [99, 99, 99]])

In [47]:
# horizontal stack
np.hstack([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

np.dstack도 있지만 잘 쓰지 않는다.

In [50]:
# Split
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [52]:
grid = np.arange(16).reshape(4, 4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
# vertical split
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [56]:
# horizontal split
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


np.dsplit도 있지만 잘 쓰지 않는다.